* The Mark and the Region

#+begin_src emacs-lisp
;;* 11 The (info "(emacs)Mark") and the Region

(leuven--chapter leuven-load-chapter-11-mark "11 The Mark and the Region"
#+end_src

** Setting the Mark

Instead of setting the *mark* in order to operate on a region, you can also type:

-  ~C-SPC C-SPC~ ::
     *"Remember" a position* in the buffer (pushes the current position to the
     *mark ring*, by setting the mark where point is without leaving it active),
     and

- ~C-u C-SPC~ ::
     Later *jump* back *to the* previous *mark* in the buffer.  You can use this
     repeatedly to *navigate* through the entire *mark ring*.

#+begin_tip
Many commands (especially ones which are liable to move you an an unknown or
arbitrary distance from your original location, like ~isearch-forward~,
~beginning-of-buffer~, ~avy~) automatically save the previous position in the mark
ring -- you don't have to use ~C-SPC C-SPC~ before, but only ~C-u C-SPC~ to return
afterwards.

So, after using ~C-s~ to go somewhere, you can easily jump back again.
#+end_tip

*** Navigating to Previous Change

*Go to* the *place* where you *last changed* something ("last edit location"):

#+begin_src emacs-lisp
    ;; Go to Last (buffer-local) Edit Location.
    (use-package goto-chg
      :load-path "site-lisp"
      :config
       (global-set-key (kbd "<C-S-backspace>") #'goto-last-change)
   )
#+end_src

It moves point through ~buffer-undo-list~ positions.

*** Navigating to Navigated Items

#+begin_src emacs-lisp
  (use-package back-button
    :config
       (back-button-mode 1)
#+end_src

You can go back and forth along the items that have been marked.

- C-x <left> ::
     Go back in buffer-local ~mark-ring~.

- C-x <right> ::
     Go forward in buffer-local ~mark-ring~.

- C-x C-<left> (or <C-M-left> in Emacs Leuven) ::
     Go back in ~global-mark-ring~.

- C-x C-<right> (or <C-M-right> in Emacs Leuven) ::
     Go forward in ~global-mark-ring~.

When the ~smartrep~ package is installed, the ~C-x~ prefix need not be used for
consecutive ~back-button~ commands.

You can also use keyboard shortcuts ~C-M-left~, or ~C-M-right~:

#+begin_src emacs-lisp
  ;; Navigate backward.
  (global-set-key (kbd "<C-M-left>")  #'back-button-global-backward) ; IntelliJ IDEA.
  ;; Navigate forward.
  (global-set-key (kbd "<C-M-right>") #'back-button-global-forward) ; IntelliJ IDEA.
  )
#+end_src

** Commands to Mark Textual Objects

- ~M-@~ ::
     Set mark after end of next *word* (~mark-word~) without moving point.

- ~C-M-@~ ::
     Set mark after end of following *balanced expression* (~mark-sexp~) without
     moving point.

Shortcuts:

| Command          | Emacs-Leuven |
|------------------+--------------|
| Extend Selection | C-M-w        |
| Shrink Selection | C-S-w        |

#+begin_src emacs-lisp
  ;; Increase selected region by semantic units.
  (use-package expand-region
    :config
    ;; ;; Key to use after an initial expand/contract to undo.
    ;; (setq expand-region-reset-fast-key "<escape> <escape>")
    (global-set-key (kbd "C-M-w") #'er/expand-region)    ; See key-chord `hh'.
    (global-set-key (kbd "C-S-w") #'er/contract-region)  ; See key-chord `HH'.
  )
#+end_src

** Operating on the Region

#+begin_src emacs-lisp
  ;; Inserting text while the mark is active causes the text in the region to be
  ;; deleted first.
  (delete-selection-mode 1)             ; Overwrite region.
#+end_src

** Shift Selection

Shifted motion keys activate the mark momentarily.

** Multiple selections

You can [[http://www.emacsrocks.com/e13.html][watch an intro to multiple-cursors at Emacs Rocks]].

In other editors:

- https://www.sublimetext.com/docs/2/multiple_selection_with_the_keyboard.html
- https://docs.c9.io/multiple_cursors.html
- http://komodoide.com/screencasts/watch/87286656-multiple-selections/

#+begin_src emacs-lisp
  ;; Multiple cursors for Emacs.
  (use-package multiple-cursors
  :config
#+end_src

*** Splitting the selection into lines

Make *batch edits* with Multiple Cursors: select a block of lines, and then *split
the region into lines* which are then *edited simultaneously*.

#+begin_src emacs-lisp
    ;; Add a cursor to each (continuous) line in the current region.
    (global-set-key (kbd "C-S-c C-S-c") #'mc/edit-lines) ;!
#+end_src

*** Quick add next/previous

Use Multiple Cursors to *rename variables quickly*: *add the next* or previous
*occurrence of the current word to the selection*, and then type the new name.
Done.

#+begin_src emacs-lisp
    ;; Add a cursor and region at the next/previous part of the buffer that
    ;; matches the current region.
    (global-set-key (kbd "C->") #'mc/mark-next-like-this) ;!
    (global-set-key (kbd "C-<") #'mc/mark-previous-like-this) ;!

    ;; Add Selection for Next Occurrence.
    (global-set-key (kbd "M-j") #'mc/mark-next-like-this) ; IntelliJ.

    ;; Unselect Occurrence. XXX
    ;; (global-set-key (kbd "M-J") #'mc/unmark-next-like-this) ; IntelliJ.

    ;; Skip the current one and select the next/previous part of the buffer that
    ;; matches the current region.
    (global-set-key (kbd "C-M->") #'mc/skip-to-next-like-this)
    (global-set-key (kbd "C-M-<") #'mc/skip-to-previous-like-this)

    ;; Add or remove caret.
    (global-set-key (kbd "<C-S-mouse-1>") #'mc/add-cursor-on-click)
    (global-set-key (kbd "<M-mouse-1>")   #'mc/add-cursor-on-click) ; XXX DOES NOT WORK.
#+end_src

*** Find All

*Add all occurrences of the current word to the selection.*

#+begin_src emacs-lisp
    ;; Select All Occurrences.
    (global-set-key (kbd "C-M-S-j") #'mc/mark-all-like-this-dwim) ;! IntelliJ.
#+end_src

#+begin_src emacs-lisp
    ;; Tries to guess what you want to mark all of.
    (global-set-key (kbd "C-;")     #'mc/mark-all-like-this-dwim) ;! Like Iedit.
    ;; (global-set-key (kbd "C-c C-w") #'mc/mark-all-like-this-dwim)
    ;; (global-set-key (kbd "C-x C-;") #'mc/mark-all-like-this-dwim)

    ;; Mark all parts of the buffer that matches the current region.
    (global-set-key (kbd "C-c C-<") #'mc/mark-all-like-this) ;!
#+end_src

#+begin_src emacs-lisp
    (global-set-key (kbd "C-!") #'mc/mark-next-symbol-like-this)
#+end_src

#+begin_src emacs-lisp
    ;; (global-set-key (kbd "<C-RET>") #'mc/mark-more-like-this-extended) ; useful for completion
#+end_src

#+begin_src emacs-lisp
    ;; Insert increasing numbers for each cursor.
    (global-set-key (kbd "C-M-=") #'mc/insert-numbers)
  )
#+end_src

*** Single Selection

To go from multiple selections to a single selection, press ~C-g~ or ~RET~.

*** Commands to run in multiple-cursors-mode

#+begin_src emacs-lisp
  ;; Multiple cursors for Emacs.
    ;; Commands to run for all cursors in multiple-cursors-mode.
    (setq mc/cmds-to-run-for-all        ; See .mc-lists.el.
          '(c-electric-slash
            cycle-spacing
            emr-show-refactor-menu
            isearch-abort
            isearch-printing-char
            js2-mode-show-node
            just-one-space
            kill-region
            leuven-fill-or-unfill-paragraph
            leuven-smart-punctuation-quotation-mark
            org-beginning-of-line
            org-end-of-line
            org-kill-line
            org-self-insert-command
            org-shiftdown
            org-shiftleft
            org-shiftright
            org-shiftup
            org-yank
            orgtbl-self-insert-command
            yas-expand))

    ;; Commands to run only once in multiple-cursors-mode.
    (setq mc/cmds-to-run-once
          '())
#+end_src

#+begin_src emacs-lisp
)                                       ; Chapter 11 ends here.
#+end_src

