* Frames and Graphical Displays

#+begin_src emacs-lisp
;;* 21 (info "(emacs)Frames") and Graphical Displays

(leuven--chapter leuven-load-chapter-21-frames "21 Frames and Graphical Displays"
#+end_src

** Mouse Commands for Editing

#+begin_src emacs-lisp
;;** 21.1 (info "(emacs)Mouse Commands")

  (leuven--section "21.1 (emacs)Mouse Commands")

  ;; Scroll one line at a time.
  (setq mouse-wheel-scroll-amount
        '(1
          ((shift) . 1)))

  ;; Paste at text-cursor, not at mouse-cursor.
  (setq mouse-yank-at-point t)
#+end_src

** Creating Frames

#+begin_src emacs-lisp
;;** 21.6 (info "(emacs)Creating Frames")

  (leuven--section "21.6 (emacs)Creating Frames")
#+end_src

1. Resize the frame to the size you want.
2. Enter ~(frame-parameters)~ in the ~*scratch*~ buffer.
3. Evaluate the form: place the cursor after the closing parenthesis, and type
   ~C-j~, so that the output goes right into the ~*scratch*~ buffer.

By putting customizations of ~default-frame-alist~ in your init file, you can
control the appearance of *all the frames* Emacs creates, including the initial
one.

#+begin_note
~initial-frame-alist~ is just for overriding properties for the first frame.
#+end_note

#+begin_src emacs-lisp
  (when (display-graphic-p)

    ;; Put Emacs exactly where you want it, every time it starts up.
    (setq initial-frame-alist
          '((top . 0)
            (left . 0)))

    ;; Auto-detect the screen dimensions and compute the height of Emacs.
    (add-to-list 'default-frame-alist
                 (cons 'height
                       (/ (-
                           ;; Height of Display 1.
                           (nth 4
                                (assq 'geometry
                                      (car (display-monitor-attributes-list)))) ; XXX Emacs 24.4 needed!
                           177)       ; Allow for Emacs' title bar and taskbar
                                      ; (from the OS).
                          (frame-char-height)))))
#+end_src

#+begin_src emacs-lisp
  ;; Title bar display of visible frames.
  (setq frame-title-format
        (format "%s Emacs%s %s%s of %s - PID: %d"
                (replace-regexp-in-string "-.*$" ""
                                          (capitalize (symbol-name system-type)))
                (if (string-match "^x86_64-.*" system-configuration)
                    "-w64"
                  "-w32")
                emacs-version
                (if (and (boundp 'emacs-repository-version)
                         emacs-repository-version)
                    (concat " (" (substring
                                  (replace-regexp-in-string
                                   " .*" "" emacs-repository-version) 0 7) ")")
                  "")
                (format-time-string "%Y-%m-%d" emacs-build-time)
                (emacs-pid)))
#+end_src

#+begin_src emacs-lisp
  (defun leuven-detach-window ()
    "Close current window and re-open it in new frame."
    (interactive)
    (let ((current-buffer (window-buffer)))
      (delete-window)
      (select-frame (make-frame))
      (set-window-buffer (selected-window) current-buffer)))
#+end_src

** Frame Commands

- ~toggle-frame-maximized~ (M-<F10> by default) ::
     Toggle maximization state of the selected frame.  Respect window manager
     screen decorations.

- ~toggle-frame-fullscreen~ (<F11> by default) ::
     Toggle fullscreen mode of the selected frame.  *Hide window manager screen
     decorations*, giving slightly more screen space to Emacs itself.

#+begin_src emacs-lisp
;;** 21.7 (info "(emacs)Frame Commands")

  (leuven--section "21.7 (emacs)Frame Commands")

  ;; Maximize Emacs frame by default.
  (modify-all-frames-parameters '((fullscreen . maximized)))

  ;; Full screen.
  (global-set-key (kbd "<C-S-f12>") #'toggle-frame-fullscreen)
#+end_src

** Speedbar Frames

#+begin_src emacs-lisp
	;;** 21.9 (info "(emacs)Speedbar")

	  (leuven--section "21.9 (emacs)Speedbar Frames")

	  ;; Everything browser (into individual source files), or Dired on steroids.
	  (use-package speedbar
		:config
		(speedbar 1)
		 (global-set-key (kbd "<f4>") #'speedbar-get-focus)
		;; Number of spaces used for indentation.
		(setq speedbar-indentation-width 2)

		;; Add new extensions for speedbar tagging (allow to expand/collapse
		;; sections, etc.) -- do this BEFORE firing up speedbar?
		(speedbar-add-supported-extension
		 '(".bib" ".css" ".jpg" ".js" ".nw" ".org" ".php" ".png" ".R" ".tex" ".txt"
		   ".w" "README"))

		;; Bind the arrow keys in the speedbar tree.
		(define-key speedbar-mode-map (kbd "<right>") #'speedbar-expand-line)
		(define-key speedbar-mode-map (kbd "<left>")  #'speedbar-contract-line)

		;; Parameters to use when creating the speedbar frame in Emacs.
		(setq speedbar-frame-parameters '((width . 30)
										  (height . 45)
										  (foreground-color . "blue")
										  (background-color . "white")))
	   (global-set-key (kbd "<f4>") #'sr-speedbar-toggle)
  )
#+end_src

See NeoTree as well.

** Scroll Bars

#+begin_src emacs-lisp
;;** 21.12 (info "(emacs)Scroll Bars")

  (leuven--section "21.12 (emacs)Scroll Bars")

  (if (and (display-graphic-p)
           ;; (featurep 'powerline)
           )

      ;; Turn scroll bar off.
      (scroll-bar-mode 1)

    ;; Position of the vertical scroll bar.
    (setq-default vertical-scroll-bar 'right))
#+end_src

** Tool Bars

#+begin_src emacs-lisp
;;** 21.15 (info "(emacs)Tool Bars")

  (leuven--section "21.15 (emacs)Tool Bars")

  ;; Turn tool bar off.
  (when (display-graphic-p)
    (tool-bar-mode 1))
#+end_src

** Using Dialog Boxes

#+begin_src emacs-lisp
;;** 21.16 Using (info "(emacs)Dialog Boxes")

  (leuven--section "21.16 (emacs)Using Dialog Boxes")

  ;; Don't use dialog boxes to ask questions.
  (setq use-dialog-box nil)

  ;; Don't use a file dialog to ask for files.
  (setq use-file-dialog nil)
#+end_src

** Tooltips

#+begin_src emacs-lisp
;;** 21.17 (info "(emacs)Tooltips")

  (leuven--section "21.17 (emacs)Tooltips")

  ;; Disable Tooltip mode (use the echo area for help and GUD tooltips).
  (unless leuven--console-p (tooltip-mode 1))
#+end_src

#+begin_src emacs-lisp
)                                       ; Chapter 21 ends here.
#+end_src

